name: Deploy to Google Cloud Run

on:
  push:
    branches: ['main', 'fix-ci']
  workflow_dispatch:

jobs:
  deploy_to_gcloud:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all branches
        run: git fetch origin 'refs/heads/*:refs/remotes/origin/*'

      - name: Ensure dev branch exists
        run: |
          if git show-ref --verify --quiet refs/heads/dev; then
              echo "Branch dev exists locally"
            else
              echo "Branch dev doesn't exist locally. Creating it."
              git checkout -b dev origin/dev
            fi

      - name: Checkout main branch
        run: git checkout main

      - name: Pull latest changes from main
        run: git pull origin main

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Determine affected projects
        id: affected
        run: |
          echo "Running Nx command..."
          npx nx reset
          npx nx show projects --affected --type=app --base=dev --verbose > affected.txt
          echo "Nx command completed with exit code $?."
          cat affected.txt

      - name: Check for affected projects
        run: |
          if [ ! -s affected.txt ]; then
            echo "No affected projects were found or an error occurred while executing the Nx command."
            exit 1
          fi

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker to use Google Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: test 0
        run: |
          # Define the repository in Google Container Registry
          GCR_REGISTRY="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY }}"
          IMAGE_TAG="${{ github.sha }}"  # Use the commit SHA as a tag to ensure uniqueness

          while IFS= read -r app; do
            echo "Building and pushing Docker image for project: $app"
            # Build the image using the app-specific Dockerfile
            echo "$GCR_REGISTRY/$app:$IMAGE_TAG"
          done < affected.txt

      - name: test
        run: |
          # Define the repository in Google Container Registry
          GCR_REGISTRY="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY }}"
          IMAGE_TAG="${{ github.sha }}"  # Use the commit SHA as a tag to ensure uniqueness

          while IFS= read -r app; do
            echo "Building and pushing Docker image for project: $app"
            safe_app=$(echo "$app" | tr '-' '_')

            # Build the image using the app-specific Dockerfile
            echo "$GCR_REGISTRY/$app:$IMAGE_TAG"
          done < affected.txt

      - name: Build, tag, and push images for affected projects
        if: success()
        run: |
          # Define the repository in Google Container Registry
          GCR_REGISTRY="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY }}"
          IMAGE_TAG="${{ github.sha }}"  # Use the commit SHA as a tag to ensure uniqueness

          while IFS= read -r app; do
            echo "Building and pushing Docker image for project: $app"
            safe_app=$(echo "$app" | tr '-' '_')
            if [[ -n "$app" ]]; then
              # Build the image using the app-specific Dockerfile
              echo "$GCR_REGISTRY/$app:$IMAGE_TAG"
            else
              echo "Nenhum projeto encontrado para $app"
            fi
          done < affected.txt
